---
title: "5069 Final Project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
setwd("/Users/bobchen/Documents/Columbia/S17/5069 Applied Data Science/Final Project/")

oakland <- read.csv("oakland.csv")
zri <- read.csv("zri_all.csv")

detach(package:timeSeries)
library(dplyr)
oakland_zri <- filter(zri, City == "Oakland")
oakland_hood <- unique(oakland_zri$RegionName)
oakland <- oakland[oakland$neighbourhood_cleansed %in% oakland_hood, ]
oakland$host_since <- as.Date(oakland$host_since)

#Create Time List

library(timeSeries)
dat <- timeSequence(from = "2010-11-01", to="2017-02-01", by="month")
dat <- as.list(dat)
neigh <- unique(oakland_zri$RegionName)

#To make into one data frame
detach(package:timeSeries)
oakland_bnb <- data.frame()
oakland_bnb[1:76, ] <- NA
for (i in neigh){
  air <- data.frame()
  for (k in dat){ 
    hood <- filter(oakland, neighbourhood_cleansed == i) 
    aird <- as.data.frame(nrow(filter(hood, host_since <= as.Date(k))))
    air <- rbind(air,aird)
  }
  colnames(air) <- i
  oakland_bnb <- cbind(air, oakland_bnb)
}

oakland_bnb <- as.data.frame(oakland_bnb)

# Change columns into time
dat <- as.data.frame(t(dat))
oakland_bnb$time <- dat$V1
rownames(oakland_bnb) <- oakland_bnb$time
oakland_bnb <- oakland_bnb[ , !(names(oakland_bnb) %in% "time")]

# Write to csv
write.csv(oakland_bnb, "oakland_bnb.csv")
```
